#!/bin/bash

$PWD/gradlew build
ssh pi@secbot "pkill java; pkill python; rm -fRv ~/secbot; mkdir ~/secbot; mkdir ~/secbot/python"
scp $PWD/pi/build/libs/*.jar pi@secbot:~/secbot/
scp $PWD/pi/src/main/python/embedded/* pi@secbot:~/secbot/python/
sleep 3
ssh pi@secbot "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar ~/secbot/pi-fat-1.0.jar  & python3 ~/secbot/python/Lidar.py"
