package com.secbot.control

enum class Device {
    SCANNING_SERVO, SCANNING_IR, SCANNING_SONAR, MOTOR_1, MOTOR_2, STEERING_SERVO, FRONT_SONAR, COMPASS_HEADING, ACCELEROMETER_X, ACCELEROMETER_Y, ACCELEROMETER_Z, DEBUG, PING, PONG

}